### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by kuhnamps** [mungewell/zoom-zt2#12]
Hi! I have tried to run the zoomzt2-gui.exe om both windows- and linuxmachines, and this happens: 
1. I run once, and it seems to work, but the effect does not in fact upload tom my zoom g1four.
2. Next time I launch the .exe, i get checksum error 0xfffffff8 on both Windows an Linux (tried both Playonlinux and Wine) and the program does not launch at all. How can I fix this?
I tried to unpack both .zip and .tar

**Comment by alexsarmiento** [comment]
The same thing happens when I try to download files from my G5N. Tested in macos11 and ubuntu 20.04. It would be nice to know which specific python module versions were used with this project by the developer.

**Comment by mungewell** [comment]
Originally the code was written under Linux (Xubuntu 16.04), and because Python is awesome I could easily adapt to making it available for Windows users.

The 'zoomzt2.py' file is really a module that the GUI uses, if you are having errors on downloading, that would presumably be this piece of code...
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2.py#L303

My pedal died (hardware failure), but will help where I can...

**Comment by mungewell** [comment]
Another thought; presently the code does very little error checking.... it could be that something else is upsetting the process and the 'checksum error' is just the symptom.

**Comment by mungewell** [comment]
This might be fixed with 
https://github.com/mungewell/zoom-zt2/commit/53bcf9a65b2780f6121e9b1da8439736fb427fd7
